const mimeTypeCategories = {
    binary: [
        'image/',
        'multipart/form-data',
        'video/',
        'application/msword',
        'application/octet-stream',
        'application/pdf',
        'application/vnd.ms-excel',
        'application/vnd.ms-powerpoint',
        'application/vnd.oasis.opendocument.text',
        'application/vnd.openxmlformats-officedocument',
        'application/zip',
        'application/x-7z-compressed',
        'application/x-rar-compressed',
        'application/x-tar',
        'application/x-bzip',
        'application/x-bzip2',
        'application/x-gzip',
        'application/vnd.android.package-archive',
        'application/vnd.visio',
        'application/x-deb',
        'application/x-rpm',
        'application/x-executable',
        'font/ttf',
        'font/otf',
        'font/woff',
        'font/woff2',
        'model/',
    ],
    json: ['application/graphql', 'application/json', 'application/ld+json', 'application/vnd.api+json'],
    text: [
        'text/', //all starting with text/
        'application/xml',
        'application/xhtml+xml',
        'application/csv',
        'application/x-www-form-urlencoded',
        'application/x-yaml',
        'application/yaml',
        'application/javascript',
        'application/sql',
        'application/rtf',
    ],
};

export default mimeTypeCategories;
