const MODEL_SCHEMA_VERSION: number = 2;
const isDev = process.env.NODE_ENV === 'DEV';

export const models = {
  Echo: {
    llm: 'Echo',
  },

  // #region SmythOS Models

  // #region OpenAI
  'smythos/gpt-4o-mini': {
    label: 'GPT 4o mini',
    modelId: 'gpt-4o-mini-2024-07-18',
    provider: 'OpenAI',
    llm: 'OpenAI', // ! DEPRECATED
    features: ['text', 'image'],
    tags: ['SmythOS'],
    tokens: 128_000,
    completionTokens: 16_383,
    enabled: true,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
  },
  'smythos/gpt-4o': {
    label: 'GPT 4o',
    modelId: 'gpt-4o-2024-08-06',
    provider: 'OpenAI',
    llm: 'OpenAI', // ! DEPRECATED
    features: ['text', 'image'],
    tags: ['SmythOS'],
    tokens: 128_000,
    completionTokens: 16_384,
    enabled: true,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
  },
  'smythos/o1': {
    label: 'GPT o1',
    modelId: 'o1-2024-12-17',
    provider: 'OpenAI',
    llm: 'OpenAI', // ! DEPRECATED
    features: ['text'],
    tags: ['SmythOS'],
    tokens: 200_000,
    completionTokens: 100_000,
    enabled: true,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
  },
  'smythos/o1-mini': {
    label: 'GPT o1 mini',
    modelId: 'o1-mini-2024-09-12',
    provider: 'OpenAI',
    llm: 'OpenAI', // ! DEPRECATED
    features: ['text'],
    tags: ['SmythOS'],
    tokens: 128_000,
    completionTokens: 65_536,
    enabled: true,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
  },
  // #endregion OpenAI

  // #region Anthropic
  'smythos/claude-3-5-sonnet': {
    label: 'Claude 3.5 Sonnet',
    modelId: 'claude-3-5-sonnet-20240620',
    provider: 'Anthropic',
    llm: 'Anthropic', // ! DEPRECATED
    features: ['text', 'image'],
    tags: ['SmythOS'],
    tokens: 200_000,
    completionTokens: 8_192,
    enabled: true,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
  },
  'smythos/claude-3.5-haiku': {
    label: 'Claude 3.5 Haiku',
    modelId: 'claude-3-5-haiku-latest',
    provider: 'Anthropic',
    llm: 'Anthropic', // ! DEPRECATED
    features: ['text'],
    tags: ['SmythOS'],
    tokens: 200_000,
    completionTokens: 8_192,
    enabled: true,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
  },
  // #endregion Anthropic

  // #region Google AI
  'smythos/gemini-2.0-flash': {
    label: 'Gemini 2.0 Flash Experimental',
    modelId: 'gemini-2.0-flash-exp',
    provider: 'GoogleAI',
    llm: 'GoogleAI', // ! DEPRECATED
    features: ['text', 'image'],
    tags: ['SmythOS'],
    tokens: 1_048_576,
    completionTokens: 8_192,
    enabled: true,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
  },
  'smythos/gemini-1.5-pro': {
    label: 'Gemini 1.5 Pro',
    modelId: 'gemini-1.5-pro',
    provider: 'GoogleAI',
    llm: 'GoogleAI', // ! DEPRECATED
    features: ['text'],
    tags: ['SmythOS'],
    tokens: 2_097_152,
    completionTokens: 8_192,
    enabled: true,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
  },
  // #endregion Google AI

  // #region Groq
  'smythos/groq-gemma2-9b': {
    label: 'Google - Gemma 2 9B',
    modelId: 'gemma2-9b-it',
    provider: 'Groq',
    llm: 'Groq', // ! DEPRECATED
    features: ['text'],
    tags: ['SmythOS'],
    tokens: 8_192,
    completionTokens: 8_192,
    enabled: true,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
  },

  'smythos/llama-3.3-70b': {
    label: 'Meta - Llama 3.3 70B',
    modelId: 'llama-3.3-70b-versatile',
    provider: 'Groq',
    llm: 'Groq', // ! DEPRECATED
    features: ['text'],
    tags: ['SmythOS'],
    tokens: 128_000,
    completionTokens: 32_768,
    enabled: true,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
  },
  // #endregion Groq

  // #endregion SmythOS Models

  // #region User Models

  // #region OpenAI
  'user/gpt-4o-mini': {
    label: 'GPT 4o mini',
    modelId: 'gpt-4o-mini-2024-07-18',
    provider: 'OpenAI',
    llm: 'OpenAI', // ! DEPRECATED
    features: ['text', 'image'],
    tags: ['Personal'],
    tokens: 0,
    completionTokens: 0,
    enabled: false,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
    keyOptions: { tokens: 128_000, completionTokens: 16_383, enabled: true },
  },
  'user/gpt-4o': {
    label: 'GPT 4o',
    modelId: 'gpt-4o-2024-08-06',
    provider: 'OpenAI',
    llm: 'OpenAI', // ! DEPRECATED
    features: ['text', 'image'],
    tags: ['Personal'],
    tokens: 0,
    completionTokens: 0,
    enabled: false,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
    keyOptions: { tokens: 128_000, completionTokens: 16_384, enabled: true },
  },
  'user/o1': {
    label: 'GPT o1',
    modelId: 'o1-2024-12-17',
    provider: 'OpenAI',
    llm: 'OpenAI', // ! DEPRECATED
    features: ['text'],
    tags: ['Personal'],
    tokens: 0,
    completionTokens: 0,
    enabled: false,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
    keyOptions: { tokens: 200_000, completionTokens: 100_000, enabled: true },
  },
  'user/o1-mini': {
    label: 'GPT o1 mini',
    modelId: 'o1-mini-2024-09-12',
    provider: 'OpenAI',
    llm: 'OpenAI', // ! DEPRECATED
    features: ['text'],
    tags: ['Personal'],
    tokens: 0,
    completionTokens: 0,
    enabled: false,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
    keyOptions: { tokens: 128_000, completionTokens: 65_536, enabled: true },
  },
  // #endregion OpenAI

  // #region Anthropic
  'user/claude-3-5-sonnet': {
    label: 'Claude 3.5 Sonnet',
    modelId: 'claude-3-5-sonnet-20240620',
    provider: 'Anthropic',
    llm: 'Anthropic', // ! DEPRECATED
    features: ['text', 'image'],
    tags: ['Personal'],
    tokens: 0,
    completionTokens: 0,
    enabled: false,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
    keyOptions: { tokens: 200_000, completionTokens: 8_192, enabled: true },
  },
  'user/claude-3.5-haiku': {
    label: 'Claude 3.5 Haiku',
    modelId: 'claude-3-5-haiku-latest',
    provider: 'Anthropic',
    llm: 'Anthropic', // ! DEPRECATED
    features: ['text'],
    tags: ['Personal'],
    tokens: 0,
    completionTokens: 0,
    enabled: false,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
    keyOptions: { tokens: 200_000, completionTokens: 8_192, enabled: true },
  },
  // #endregion Anthropic

  // #region Google AI
  'user/gemini-2.0-flash': {
    label: 'Gemini 2.0 Flash Experimental',
    modelId: 'gemini-2.0-flash-exp',
    provider: 'GoogleAI',
    llm: 'GoogleAI', // ! DEPRECATED
    features: ['text', 'image'],
    tags: ['Personal'],
    tokens: 0,
    completionTokens: 0,
    enabled: false,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
    keyOptions: { tokens: 1_048_576, completionTokens: 8_192, enabled: true },
  },
  'user/gemini-1.5-pro': {
    label: 'Gemini 1.5 Pro',
    modelId: 'gemini-1.5-pro',
    provider: 'GoogleAI',
    llm: 'GoogleAI', // ! DEPRECATED
    features: ['text'],
    tags: ['Personal'],
    tokens: 0,
    completionTokens: 0,
    enabled: false,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
    keyOptions: { tokens: 2_097_152, completionTokens: 8_192, enabled: true },
  },
  // #endregion Google AI

  // #region Groq
  'user/groq-gemma2-9b': {
    label: 'Google - Gemma 2 9B',
    modelId: 'gemma2-9b-it',
    provider: 'Groq',
    llm: 'Groq', // ! DEPRECATED
    features: ['text'],
    tags: ['Personal'],
    tokens: 0,
    completionTokens: 0,
    enabled: false,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
    keyOptions: { tokens: 8_192, completionTokens: 8_192, enabled: true },
  },

  'user/llama-3.3-70b': {
    label: 'Meta - Llama 3.3 70B',
    modelId: 'llama-3.3-70b-versatile',
    provider: 'Groq',
    llm: 'Groq', // ! DEPRECATED
    features: ['text'],
    tags: ['Personal'],
    tokens: 0,
    completionTokens: 0,
    enabled: false,
    hidden: MODEL_SCHEMA_VERSION !== 2 || !isDev,
    keyOptions: { tokens: 128_000, completionTokens: 32_768, enabled: true },
  },
  // #endregion Groq

  // #endregion User Models

  //#region [legacy models] ==============================================================
  // DeepSeek
  'deepseek-v2.5': {
    llm: 'DeepSeek',
    baseURL: 'https://api.deepseek.com/beta',
    alias: 'deepseek-chat',
  },
  'deepseek-chat': {
    llm: 'DeepSeek',
    baseURL: 'https://api.deepseek.com/beta',
    tokens: 128000,
    completionTokens: 8192,
    enabled: false,
    keyOptions: { tokens: 128000, completionTokens: 8192 },
  },

  // GPT-4o
  'gpt-4o-mini': {
    llm: 'OpenAI',
    alias: 'gpt-4o-mini-2024-07-18',
    components: [
      'PromptGenerator',
      'LLMAssistant',
      'Classifier',
      'VisionLLM',
      'AgentPlugin',
      'Chatbot',
      'GPTPlugin',
      'GenAILLM',
    ],
    features: ['text', 'image'],
  },
  'gpt-4o-mini-2024-07-18': {
    llm: 'OpenAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: true,
    keyOptions: { tokens: 128000, completionTokens: 16383 },
  },
  'gpt-4o': {
    llm: 'OpenAI',
    alias: 'gpt-4o-2024-08-06',
    components: [
      'PromptGenerator',
      'LLMAssistant',
      'Classifier',
      'VisionLLM',
      'AgentPlugin',
      'Chatbot',
      'GPTPlugin',
      'GenAILLM',
    ],
    features: ['text', 'image'],
  },
  'gpt-4o-2024-08-06': {
    llm: 'OpenAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: true,
    keyOptions: { tokens: 128000, completionTokens: 16384 },
  },

  // o1 models
  o1: {
    llm: 'OpenAI',
    alias: 'o1-2024-12-17',
    components: ['PromptGenerator', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
  },
  'o1-2024-12-17': {
    llm: 'OpenAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: true,
    keyOptions: { tokens: 200_000, completionTokens: 100_000 },
  },
  'o1-mini': {
    llm: 'OpenAI',
    alias: 'o1-mini-2024-09-12',
    components: ['PromptGenerator', 'GenAILLM'],
    features: ['text'],
  },
  'o1-mini-2024-09-12': {
    llm: 'OpenAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: true,
    keyOptions: { tokens: 128_000, completionTokens: 65_536 },
  },
  'o1-preview': {
    llm: 'OpenAI',
    alias: 'o1-preview-2024-09-12',
    components: ['PromptGenerator', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
  },
  'o1-preview-2024-09-12': {
    llm: 'OpenAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: true,
    keyOptions: { tokens: 128_000, completionTokens: 32_768 },
  },

  // GPT-4-turbo
  'gpt-4-turbo-latest': {
    llm: 'OpenAI',
    alias: 'gpt-4-turbo-2024-04-09',
    components: ['PromptGenerator', 'LLMAssistant', 'Classifier'],
    tags: ['legacy'],
  },
  'gpt-4-turbo': {
    llm: 'OpenAI',
    alias: 'gpt-4-turbo-2024-04-09',
    components: [
      'PromptGenerator',
      'LLMAssistant',
      'VisionLLM',
      'GPTPlugin',
      'AgentPlugin',
      'Chatbot',
    ],
    tags: ['legacy'],
  },
  'gpt-4-turbo-2024-04-09': {
    llm: 'OpenAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: true,
    keyOptions: { tokens: 128000, completionTokens: 4096 },
  },

  // GPT-4
  'gpt-4-latest': {
    llm: 'OpenAI',
    alias: 'gpt-4-0613',
    enabled: true,
    components: ['PromptGenerator', 'LLMAssistant'],
    tags: ['legacy'],
  },
  'gpt-4': {
    llm: 'OpenAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: true,
    keyOptions: { tokens: 8192, completionTokens: 8192 },
    components: [
      'PromptGenerator',
      'LLMAssistant',
      'Classifier',
      'GPTPlugin',
      'AgentPlugin',
      'Chatbot',
    ],
    tags: ['legacy'],
  },
  'gpt-4-0613': {
    llm: 'OpenAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: true,
    hidden: true,
    keyOptions: { tokens: 8192, completionTokens: 8192 },
  },

  // GPT-3.5
  'gpt-3.5-turbo-latest': {
    llm: 'OpenAI',
    alias: 'gpt-3.5-turbo-0125',
    components: [
      'PromptGenerator',
      'LLMAssistant',
      'Classifier',
      'GPTPlugin',
      'AgentPlugin',
      'Chatbot',
    ],
    tags: ['legacy'],
  },
  'gpt-3.5-turbo': {
    llm: 'OpenAI',
    alias: 'gpt-3.5-turbo-0125',
    components: [
      'PromptGenerator',
      'LLMAssistant',
      'Classifier',
      'GPTPlugin',
      'AgentPlugin',
      'Chatbot',
    ],
    tags: ['legacy'],
  },
  'gpt-3.5-turbo-0125': {
    llm: 'OpenAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: true,
    keyOptions: { tokens: 16385, completionTokens: 4096 },
  },
  'gpt-3.5-turbo-1106': {
    llm: 'OpenAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: true,
    keyOptions: { tokens: 16384, completionTokens: 4096 },
    //components: ['PromptGenerator', 'LLMAssistant'],
    tags: ['legacy'],
  },

  'gpt-3.5-turbo-16k': {
    llm: 'OpenAI',
    alias: 'gpt-3.5-turbo-0125',
    //components: ['PromptGenerator', 'LLMAssistant'],
    tags: ['legacy'],
  },

  // Anthropic
  'claude-3.5-haiku': {
    llm: 'Anthropic',
    alias: 'claude-3-5-haiku-latest',
    components: [
      'PromptGenerator',
      'LLMAssistant',
      'Classifier',
      'AgentPlugin',
      'Chatbot',
      'GenAILLM',
    ],
    features: ['text'],
    tags: ['new'],
  },
  'claude-3-5-haiku-latest': {
    llm: 'Anthropic',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 200000, completionTokens: 8192, enabled: true },
  },
  'claude-3-5-sonnet-latest': {
    llm: 'Anthropic',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 200000, completionTokens: 8192, enabled: true },
    components: [
      'PromptGenerator',
      'LLMAssistant',
      'Classifier',
      'VisionLLM',
      'AgentPlugin',
      'Chatbot',
      'GenAILLM',
    ],
    features: ['text', 'image'],
  },
  'claude-3.5-sonnet': {
    llm: 'Anthropic',
    alias: 'claude-3-5-sonnet-20240620',
    components: [
      'PromptGenerator',
      'LLMAssistant',
      'Classifier',
      'VisionLLM',
      'AgentPlugin',
      'Chatbot',
      'GenAILLM',
    ],
    features: ['text', 'image'],
  },
  'claude-3-5-sonnet-20240620': {
    llm: 'Anthropic',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 200000, completionTokens: 8192, enabled: true },
  },
  'claude-3-opus': {
    llm: 'Anthropic',
    alias: 'claude-3-opus-20240229',
    components: [
      'PromptGenerator',
      'LLMAssistant',
      'Classifier',
      'VisionLLM',
      'AgentPlugin',
      'Chatbot',
      'GenAILLM',
    ],
    features: ['text', 'image'],
  },
  'claude-3-opus-20240229': {
    llm: 'Anthropic',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 200000, completionTokens: 4096, enabled: true },
  },
  'claude-3-sonnet': {
    llm: 'Anthropic',
    alias: 'claude-3-sonnet-20240229',
    components: [
      'PromptGenerator',
      'LLMAssistant',
      'Classifier',
      'VisionLLM',
      'AgentPlugin',
      'Chatbot',
    ],
    tags: ['deprecated'],
  },
  'claude-3-sonnet-20240229': {
    llm: 'Anthropic',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 200000, completionTokens: 4096, enabled: true },
  },
  'claude-3-haiku': {
    llm: 'Anthropic',
    alias: 'claude-3-haiku-20240307',
    components: [
      'PromptGenerator',
      'LLMAssistant',
      'Classifier',
      'VisionLLM',
      'AgentPlugin',
      'Chatbot',
    ],
    tags: ['legacy'],
  },
  'claude-3-haiku-20240307': {
    llm: 'Anthropic',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 200000, completionTokens: 4096, enabled: true },
  },
  'claude-2.1': {
    llm: 'Anthropic',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 200000, completionTokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'Classifier'],
    tags: ['legacy'],
  },
  'claude-instant-1.2': {
    llm: 'Anthropic',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 100000, completionTokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'Classifier'],
    tags: ['legacy'],
  },

  /*** Models from Google AI ***/

  // Gemini 1.5 pro
  'gemini-1.5-pro-latest': {
    llm: 'GoogleAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 2097152, completionTokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'VisionLLM', 'MultimodalLLM'],
    tags: ['legacy'],
  },
  'gemini-1.5-pro-exp-0801': {
    llm: 'GoogleAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 2097152, completionTokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'VisionLLM', 'MultimodalLLM', 'GenAILLM'],
    features: ['text', 'image', 'video', 'audio', 'document'],
  },
  'gemini-1.5-pro-latest-stable': {
    llm: 'GoogleAI',
    alias: 'gemini-1.5-pro',
    components: ['PromptGenerator', 'LLMAssistant', 'VisionLLM', 'MultimodalLLM', 'GenAILLM'],
    features: ['text', 'image', 'video', 'audio', 'document'],
  },
  'gemini-1.5-pro-stable': {
    llm: 'GoogleAI',
    alias: 'gemini-1.5-pro-001',
    components: ['PromptGenerator', 'LLMAssistant', 'VisionLLM', 'MultimodalLLM', 'GenAILLM'],
    features: ['text', 'image', 'video', 'audio', 'document'],
  },
  'gemini-1.5-pro': {
    llm: 'GoogleAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 2097152, completionTokens: 8192, enabled: true },
  },
  'gemini-1.5-pro-001': {
    llm: 'GoogleAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 2097152, completionTokens: 8192, enabled: true },
  },

  // Gemini 1.5 flash
  'gemini-1.5-flash-latest': {
    llm: 'GoogleAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 1048576, completionTokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'VisionLLM', 'MultimodalLLM'],
    tags: ['legacy'],
  },
  'gemini-1.5-flash-latest-stable': {
    llm: 'GoogleAI',
    alias: 'gemini-1.5-flash',
    components: ['PromptGenerator', 'LLMAssistant', 'VisionLLM', 'MultimodalLLM'],
    tags: ['legacy'],
  },
  'gemini-1.5-flash-stable': {
    llm: 'GoogleAI',
    alias: 'gemini-1.5-flash-001',
    components: ['PromptGenerator', 'LLMAssistant', 'VisionLLM', 'MultimodalLLM', 'GenAILLM'],
    features: ['text', 'image', 'video', 'audio', 'document'],
  },
  'gemini-1.5-flash': {
    llm: 'GoogleAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 1048576, completionTokens: 8192, enabled: true },
  },
  'gemini-1.5-flash-001': {
    llm: 'GoogleAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 1048576, completionTokens: 8192, enabled: true },
  },

  // Gemini 1.0 pro
  'gemini-1.0-pro-latest': {
    llm: 'GoogleAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 30720, completionTokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant'],
    tags: ['legacy'],
  },
  'gemini-1.0-pro-latest-stable': {
    llm: 'GoogleAI',
    alias: 'gemini-1.0-pro',
    components: ['PromptGenerator', 'LLMAssistant'],
    tags: ['legacy'],
  },
  'gemini-1.0-pro-stable': {
    llm: 'GoogleAI',
    alias: 'gemini-1.0-pro-001',
    components: ['PromptGenerator', 'LLMAssistant'],
    tags: ['legacy'],
  },
  'gemini-1.0-pro': {
    llm: 'GoogleAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 30720, completionTokens: 8192, enabled: true },
  },
  'gemini-1.0-pro-001': {
    llm: 'GoogleAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 30720, completionTokens: 8192, enabled: true },
  },
  'gemini-pro-vision': {
    llm: 'GoogleAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 12288, completionTokens: 4096, enabled: true },
    components: ['VisionLLM'],
    tags: ['legacy'],
  },

  // Groq
  'llama-3.2-1b-preview': {
    llm: 'Groq',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, completionTokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
  },
  'llama-3.2-3b-preview': {
    llm: 'Groq',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, completionTokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
  },
  'llama-3.2-11b-vision-preview': {
    llm: 'Groq',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, completionTokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'VisionLLM', 'GenAILLM'],
    features: ['text', 'image'],
    tags: ['new'],
  },
  'llama-guard-3-8b': {
    llm: 'Groq',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, completionTokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
  },
  'llava-v1.5-7b-4096-preview': {
    llm: 'Groq',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, completionTokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
  },
  'groq-llama-3.1-405b-reasoning': {
    llm: 'Groq',
    alias: 'llama-3.1-405b-reasoning',
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
  },
  'llama-3.1-405b-reasoning': {
    llm: 'Groq',
    tokens: 16000,
    completionTokens: 16000,
    enabled: false,
    keyOptions: { tokens: 131072, completionTokens: 131072, enabled: true },
  },
  'groq-llama-3.1-70b-versatile': {
    llm: 'Groq',
    alias: 'llama-3.1-70b-versatile',
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
  },
  'llama-3.1-70b-versatile': {
    llm: 'Groq',
    tokens: 8000,
    completionTokens: 8000,
    enabled: false,
    keyOptions: { tokens: 131072, completionTokens: 131072, enabled: true },
  },
  'groq-llama-3.1-8b-instant': {
    llm: 'Groq',
    alias: 'llama-3.1-8b-instant',
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
  },
  'llama-3.1-8b-instant': {
    llm: 'Groq',
    tokens: 8000,
    completionTokens: 8000,
    enabled: false,
    keyOptions: { tokens: 131072, completionTokens: 131072, enabled: true },
  },
  'llama3-groq-70b-8192-tool-use-preview': {
    llm: 'Groq',
    tokens: 8192,
    completionTokens: 8192,
    enabled: false,
    keyOptions: { tokens: 8192, completionTokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
  },
  'llama3-groq-8b-8192-tool-use-preview': {
    llm: 'Groq',
    tokens: 8192,
    completionTokens: 8192,
    enabled: false,
    keyOptions: { tokens: 8192, completionTokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
  },
  'groq-llama3-8b': {
    llm: 'Groq',
    alias: 'llama3-8b-8192',
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
  },
  'llama3-8b-8192': {
    llm: 'Groq',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, completionTokens: 8192, enabled: true },
  },
  'groq-llama3-70b': {
    llm: 'Groq',
    alias: 'llama3-70b-8192',
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
  },
  'llama3-70b-8192': {
    llm: 'Groq',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, completionTokens: 8192, enabled: true },
  },
  'groq-llama2-70b': {
    llm: 'Groq',
    alias: 'llama2-70b-4096',
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
  },
  'llama2-70b-4096': {
    llm: 'Groq',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, completionTokens: 4096, enabled: true },
  },
  'groq-mixtral-8x7b': {
    llm: 'Groq',
    alias: 'mixtral-8x7b-32768',
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
  },
  'mixtral-8x7b-32768': {
    llm: 'Groq',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, completionTokens: 32768, enabled: true },
  },
  'groq-gemma-7b': {
    llm: 'Groq',
    alias: 'gemma-7b-it',
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
  },
  'gemma-7b-it': {
    llm: 'Groq',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, completionTokens: 8192, enabled: true },
  },
  'groq-gemma2-9b': {
    llm: 'Groq',
    alias: 'gemma2-9b-it',
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
  },
  'gemma2-9b-it': {
    llm: 'Groq',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, completionTokens: 8192, enabled: true },
  },

  // Together AI
  'zero-one-ai/Yi-34B-Chat': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['LLMAssistant'], // * Excluded from 'PromptGenerator' (has "```json...```" with JSON response)
    baseURL: 'https://api.together.xyz/v1',
  },
  'Austism/chronos-hermes-13b': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 2048, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },

  // Together AI - Meta
  'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo': {
    llm: 'TogetherAI',
    tokens: 4096,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['LLMAssistant', 'PromptGenerator', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo': {
    llm: 'TogetherAI',
    tokens: 4096,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['LLMAssistant', 'PromptGenerator', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo': {
    llm: 'TogetherAI',
    tokens: 4096,
    enabled: false,
    keyOptions: { tokens: 130815, enabled: true },
    components: ['LLMAssistant', 'PromptGenerator', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'meta-llama/Meta-Llama-3-8B-Instruct-Turbo': {
    llm: 'TogetherAI',
    tokens: 4096,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['LLMAssistant', 'PromptGenerator', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'meta-llama/Meta-Llama-3-70B-Instruct-Turbo': {
    llm: 'TogetherAI',
    tokens: 4096,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['LLMAssistant', 'PromptGenerator', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'meta-llama/Meta-Llama-3-8B-Instruct-Lite': {
    llm: 'TogetherAI',
    tokens: 4096,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['LLMAssistant', 'PromptGenerator', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'meta-llama/Meta-Llama-3-70B-Instruct-Lite': {
    llm: 'TogetherAI',
    tokens: 4096,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['LLMAssistant', 'PromptGenerator', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'codellama/CodeLlama-13b-Instruct-hf': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'codellama/CodeLlama-34b-Instruct-hf': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'codellama/CodeLlama-70b-Instruct-hf': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'codellama/CodeLlama-7b-Instruct-hf': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 16384, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'meta-llama/Llama-2-70b-chat-hf': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'meta-llama/Llama-2-13b-chat-hf': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['LLMAssistant'], // * Excluded from 'PromptGenerator' (has introductory text with JSON response)
    baseURL: 'https://api.together.xyz/v1',
  },
  'meta-llama/Llama-2-7b-chat-hf': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['LLMAssistant'], // * Excluded from 'PromptGenerator' (has introductory text with JSON response)
    baseURL: 'https://api.together.xyz/v1',
  },
  'meta-llama/Llama-3-8b-chat-hf': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'meta-llama/Llama-3-70b-chat-hf': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'meta-llama/Llama-Vision-Free': {
    llm: 'TogetherAI',
    tokens: 4096,
    enabled: false,
    keyOptions: { tokens: 131072, enabled: true },
    components: ['LLMAssistant', 'PromptGenerator', 'VisionLLM', 'GenAILLM'],
    features: ['text', 'image'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo': {
    llm: 'TogetherAI',
    tokens: 4096,
    enabled: false,
    keyOptions: { tokens: 131072, enabled: true },
    components: ['LLMAssistant', 'PromptGenerator', 'VisionLLM', 'GenAILLM'],
    features: ['text', 'image'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo': {
    llm: 'TogetherAI',
    tokens: 4096,
    enabled: false,
    keyOptions: { tokens: 131072, enabled: true },
    components: ['LLMAssistant', 'PromptGenerator', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'togethercomputer/falcon-7b-instruct': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 2048, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },

  // Together AI - Mistral
  'mistralai/Mistral-7B-Instruct-v0.1': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'mistralai/Mistral-7B-Instruct-v0.2': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'mistralai/Mistral-7B-Instruct-v0.3': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'Classifier', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'mistralai/Mixtral-8x7B-Instruct-v0.1': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'Classifier', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'mistralai/Mixtral-8x22B-Instruct-v0.1': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 65536, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'Gryphe/MythoMax-L2-13b': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },

  // Together AI - NousResearch
  'NousResearch/Nous-Capybara-7B-V1p9': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'NousResearch/Nous-Hermes-2-Mistral-7B-DPO': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'NousResearch/Nous-Hermes-2-Mixtral-8x7B-SFT': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'NousResearch/Nous-Hermes-2-Yi-34B': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'NousResearch/Nous-Hermes-llama-2-7b': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'NousResearch/Nous-Hermes-Llama2-13b': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },

  // Together AI - OpenChat
  'openchat/openchat-3.5-1210': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },

  // Together AI - Teknium
  'teknium/OpenHermes-2-Mistral-7B': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'teknium/OpenHermes-2p5-Mistral-7B': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'garage-bAInd/Platypus2-70B-instruct': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'upstage/SOLAR-10.7B-Instruct-v1.0': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'togethercomputer/StripedHyena-Nous-7B': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'lmsys/vicuna-7b-v1.5': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'lmsys/vicuna-13b-v1.5': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },

  // Together AI - Allen AI
  'allenai/OLMo-7B-Twin-2T': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 2048, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'allenai/OLMo-7B': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 2048, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },

  // Together AI - Qwen
  'Qwen/Qwen1.5-0.5B-Chat': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['LLMAssistant'], // * Excluded from 'PromptGenerator' (has introductory text with JSON response)
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'Qwen/Qwen1.5-1.8B-Chat': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'Qwen/Qwen1.5-4B-Chat': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'Qwen/Qwen1.5-7B-Chat': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'Qwen/Qwen1.5-14B-Chat': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'Qwen/Qwen1.5-32B-Chat': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'Qwen/Qwen1.5-72B-Chat': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'Qwen/Qwen1.5-110B-Chat': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },

  // Together AI - DeepSeek
  'deepseek-ai/deepseek-coder-33b-instruct': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 16384, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'deepseek-ai/deepseek-llm-67b-chat': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },

  // Together AI - Google
  'google/gemma-2b-it': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'google/gemma-7b-it': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'google/gemma-2-9b-it': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'google/gemma-2-27b-it': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },

  // Together AI - Undi95
  'Undi95/Toppy-M-7B': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },

  // Together AI - Others
  'cognitivecomputations/dolphin-2.5-mixtral-8x7b': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'databricks/dbrx-instruct': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'Open-Orca/Mistral-7B-OpenOrca': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 8192, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'snorkelai/Snorkel-Mistral-PairRM-DPO': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 32768, enabled: true },
    components: ['LLMAssistant'], // * Excluded from 'PromptGenerator' (has some other text)
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'Snowflake/snowflake-arctic-instruct': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'togethercomputer/alpaca-7b': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 2048, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'WizardLM/WizardLM-13B-V1.2': {
    llm: 'TogetherAI',
    tokens: 2048,
    enabled: false,
    keyOptions: { tokens: 4096, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    baseURL: 'https://api.together.xyz/v1',
  },
  'microsoft/WizardLM-2-8x22B': {
    llm: 'TogetherAI',
    tokens: 65536,
    enabled: false,
    keyOptions: { tokens: 65536, enabled: true },
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
    baseURL: 'https://api.together.xyz/v1',
  },

  // We do not get the exact token information for Dalle models, so use the maximum possible values
  'dall-e-3': {
    llm: 'OpenAI',
    alias: 'dall-e-3',
    enabled: true,
    components: ['ImageGenerator'],
    tokens: 2048,
    completionTokens: 2048,
    keyOptions: { tokens: 128000, completionTokens: 16383 },
  },
  'dall-e-2': {
    llm: 'OpenAI',
    alias: 'dall-e-2',
    enabled: true,
    components: ['ImageGenerator'],
    tokens: 2048,
    completionTokens: 2048,
    keyOptions: { tokens: 128000, completionTokens: 16383 },
  },

  // xAI models
  grok: {
    llm: 'xAI',
    alias: 'grok-beta',
    components: ['PromptGenerator', 'LLMAssistant', 'GenAILLM'],
    features: ['text'],
    tags: ['new'],
  },
  'grok-beta': {
    llm: 'xAI',
    tokens: 2048,
    completionTokens: 2048,
    enabled: false,
    keyOptions: {
      tokens: 131072,
      completionTokens: 4096, // assumed
      enabled: true,
    },
    baseURL: 'https://api.x.ai/v1',
  },

  //#endregion [legacy models] ==============================================================
} as const;

export type LLMProvider = (typeof models)[keyof typeof models]['llm'] | 'VertexAI' | 'Bedrock';
export type LLMModel = keyof typeof models ;
export type LLMModelInfo = (typeof models)[LLMModel];

